### ISSUE TITLE
Push images into a Docker Hub repository

### ISSUE THREAD

**Issue by calebespinoza** [bc-lt-at-fs-03-devops/banking-web-ui#10]
As a operator, I need to store every new stable container image built with the latest changes in the app's source code, which will help me to deploy the app in different environments.

**Acceptance Criteria**
-
- A new public/private repo should be created in a Docker Hub account.
- A Personal Access Token should be used to login to the Docker Hub account through `docker login`.
- The new image should be tag with a incremental numeric version.
- The new image should be stored in the repo properly.

**Sources**
-
* [docker push](https://docs.docker.com/engine/reference/commandline/push/)
* [docker login](https://docs.docker.com/engine/reference/commandline/login/)

**Deadline**
-
Tuesday 7th, 2023

**Comment by aolguin89** [comment]
Thanks to @kevingaray for this great [Guide](https://github.com/bc-lt-at-fs-03-devops/banking-api/issues/15#issuecomment-1458614499)
