### ISSUE TITLE
Create and provision the infrastructure for the Web UI

### ISSUE THREAD

**Issue by calebespinoza** [bc-lt-at-fs-03-devops/banking-web-ui#17]
As an operator, I need to provision the infrastructure where the Web UI app will be deployed.

**Acceptance Criteria**
-
- A new Ubuntu server should be created in the Cloud provider applying the constrains for the free tier.
- The server should be provisioned with Docker Engine.
- Only the ports 22 (SSH) and 8050 (TCP) should be opened for inbound traffic.
- The server should have internet connection.

**Deadline**
-
Tuesday 14th, 2023

**Comment by DMGochoa** [comment]
![Image](https://user-images.githubusercontent.com/100704377/225111999-d5e7fb28-4ddc-4379-aec5-bfb8e7371eba.png)

Now the UIweb is in a EC2 instance and is conected to the api EC2 instance.

@calebespinoza

**Comment by DMGochoa** [comment]
- Enter to to the login
   - http://54.234.2.211:8050/login
- User test data
   - username: SCollecott
   - password: St2011
   - code: 63594642
