### ISSUE TITLE
Run container using Docker Compose

### ISSUE THREAD

**Issue by calebespinoza** [bc-lt-at-fs-03-devops/banking-web-ui#8]
As a developer and/or operator, I need to declare the new container in a docker-compose file, which will help me to deploy and manage the container in different environments.

**Acceptance Criteria**
-
* A `docker-compose.yaml` file should be created at the root of the repo.
* The compose file should describe all the configs to run the container.

**Sources**
-
* [Compose file specification](https://docs.docker.com/compose/compose-file/)

**Deadline**
-
Wednesday 8th, 2023

**Comment by DMGochoa** [comment]
To run the docker compose first we need to build the image
- `docker-compose build` or `docker compose build`
Now we can run the image
- `docker-compose up -d` or `docker compose up -d`
To saw the volumes
- `docker-compose ps` or `docker compose ps`

**Comment by calebespinoza** [comment]
I added an obs in the PR, please take a look.

**Comment by DMGochoa** [comment]
Hi, the merge conflict is now solved
